version: '3.8'

services:
  web:
    build: .
    env_file: .env
    container_name: fastapi_app
    ports:
      - "8000:80"
    # This should match the CMD from the Dockerfile or be complete if defined here
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-dir /code
    networks:
      - fastapi_app_network
    volumes:
      - .:/code

networks:
  fastapi_app_network:
    driver: bridge
